### PR TITLE
Optimize the user experience:

### PR DESCRIPTION
**Pull request by makerbase-mks**
1.  Add "disconnect" button
2. Add "Fan" and "Motor" buttons
3. Jump to the monitoring page when the printer is connected
4. Compatible with Cura 3.X version
5. Modify multiple languages
6. SD card files cannot be queried during printing
7. Added the failure to transfer files, and only one file can be transferred at the same time.

### CODE REVIEW

**Comment by makerbase-mks** [comment]
1. Add "disconnect" button
2. Add "Fan" and "Motor" buttons
3. Jump to the monitoring page when the printer is connected
4. Compatible with 3.X version
5. Modify multiple languages
6. SD card files cannot be queried during printing
7. Added the failure to transfer files, and only one file can be transferred at the same time.

**Comment by makerbase-mks** [comment]
How is the test?

**Comment by Elaugaste** [comment]
Printing in the air because after transferring gcode to sdcard, file contains http headers. 
i fix this, check my pull request

**Comment by Jeredian** [comment]
@Elaugaste , that's great. Today I'll look at it, and merge to master.

**Pull request merged**
