### PR TITLE
How to use plugin from Cura Marketplace

### PR DESCRIPTION
**Pull request by Jeredian**

### CODE REVIEW

**Comment by Jeredian** [comment]
Plugin submitted to Marketplace, waiting for a time when it will be approved

**Comment by Jeredian** [comment]
linked with #1

**Comment by Ghostkeeper** [comment]
Reviewing this today ;)

**Comment by Jeredian** [comment]
@Ghostkeeper , thanks for reviewing.
After plugin publication one company wants to place a similar one plugin but for its printer brand. What kind of differences is needed to make this? Except for different plugin id and logo.

**Comment by Ghostkeeper** [comment]
You mean, the code is exactly the same but then branded? I mean, why not just use your plug-in and instruct people to download that?

If they want to brand it with a different plug-in ID and logo, they are allowed to according to your license as long as they publish their source code.

If their printer brand has a different protocol, they would need to take a look at the OctoPrint plug-in or your plug-in and modify it as they need. There are several protocols involved here:
* Discovering printers on the network. Pretty much everyone uses Zeroconf for this since it's the easiest for the user. In your case the plug-in filters the zeroconf devices on the network by the protocol `_mks`. In Ultimaker's case they filter by something else and OctoPrint I don't know by heart but it's probably similar.
* Communicating configurations. Some printers can tell Cura which nozzle + material they have loaded which makes it easier for the user to sync with the printer. Your plug-in doesn't do this.
* Communicating printer status, like current print or camera images. Your plug-in opens a web stream to an MJPEG camera file on the printer's IP. Makes sense, but if their printer works differently it needs to be adjusted.
* Sending the print over. Your plug-in seems to be specific to g-code so if they use a different protocol it'll need to be adjusted. The method of transfer is again just TCP so I think pretty much anyone uses that.

It should be noted that for the discovery, we have a protocol in Cura 4.4 that your plug-in doesn't use. It means that the discovered printers won't appear in the list of network-connected printers when you add a new printer. Take a look at the [OctoPrint plug-in](https://github.com/fieldOfView/Cura-OctoPrintPlugin) for an example of how that's done.

**Comment by Jeredian** [comment]
Thanks for answering. I thought the same things about branding but weren't sure.
About the plugin, thanks for the advice. I planned to add auto-discovery existed printers, like in OctoPrint in the next releases.

**Pull request merged**
