### PR TITLE
reconnect loop and some design fix for cura 5

### PR DESCRIPTION
**Pull request by iqubik**
reconnect loop and some design fix for cura 5
image

### CODE REVIEW

**Comment by Jeredian** [comment]
@iqubik , thanks for your pull request. Please look at the #293 changes and fix existing conflicts.

**Comment by ParkerK** [comment]
Hi @iqubik the loop should be fixed in https://github.com/Jeredian/mks-wifi-plugin/pull/290 - are you still having issues with it after using those changes?

**Comment by morsamatias** [comment]
@ParkerK The problem with the reconnect loop is still happening, the branch #290 didn't fix it.

**Comment by ParkerK** [comment]
@morsamatias - are you using the plugin version from the marketplace or did you download the latest branch from Github?

**Comment by Jeredian** [comment]
PR closed because most of the style issues was solved in #293 .
The "loop" issue that we have right now not related to the enum value. It happens because of the old settings. It will be solved in #271

**Pull request closed without merging**
